#!/bin/bash

set -x
set -e
set -u

# Cleanup
rm -rf ${GIT_REPO} || :

# Pull down the submodule repo
if ! ( git clone ${GIT_CLONE_URL} ); then
    echo "Unable to clone repository: ${GIT_CLONE_URL}"
    exit 1
fi

# Setup chef to use our jenkins server
# cp -r ~/.chef chef-cookbooks

# Merge the proposed patch(es)
cd ${GIT_REPO}
if ! ( curl -s ${GIT_PATCH_URL} | git am ); then
    echo "Unable to merge proposed patch: ${GIT_PATCH_URL}"
    exit 1
fi
cd ..

# Upload the cookbook
#echo "Uploading ${GIT_REPO} Cookbook"
#if ! ( knife cookbook upload -o . ${GIT_REPO} ); then
#    echo "Unable to upload ${GIT_REPO} cookbook to chef-server"
#    exit 1
#fi
echo "Uploading all Cookbooks"
if ! ( knife cookbook upload -o . -a ); then
    echo "Unable to upload cookbooks to chef-server"
    exit 1
fi

# Cleanup after ourselves
rm -rf ${GIT_REPO}

curl -s -K ~/.rcbjenkins-git-creds ${GIT_COMMENT_URL} -X 'POST' -d '{"body": "Gate: Chef Server upload\n * '${BUILD_URL}'consoleFull : SUCCESS"}'
