#!/bin/bash

set -x
set -e
set -u

# Cleanup
rm -rf ${GIT_REPO} || :

# Clone the upstream repo
if ! ( git clone ${GIT_CLONE_URL} ); then
    echo "Unable to clone git repo: ${GIT_CLONE_URL}"
    exit 1
fi

# Merge the proposed patch(es)
cd ${GIT_REPO}
if ! ( curl -s ${GIT_PATCH_URL} | git am ); then
    echo "Unable to merge proposed patch: ${GIT_PATCH_URL}"
    exit 1
fi

# Check the syntax for all ruby files
if ! ( find . -type f -name \*.rb -exec ruby --verbose -c {} + ); then
    echo "Found Ruby syntax errors"
    exit 1
fi

# Check the syntax for all erubis files
if ! ( find . -type f -name \*.rb -exec erubis -z {} + ); then
    echo "Found Erubis syntax errors"
    exit 1
fi

# Cleanup after ourselves
cd ..
rm -rf ${GIT_REPO}

curl -s -K ~/.rcbjenkins-git-creds ${GIT_COMMENT_URL} -X 'POST' -d '{"body": "Gate: Submodule syntax\n * '${BUILD_URL}'consoleFull : SUCCESS"}'
