#!/bin/bash
#
# $1 = test repo number
#

# force a local default so this can be run on command line
DISTRELEASE=${DISTRELEASE-ubuntu-natty}
MILESTONE=${MILESTONE-d5}

[ -e $(dirname $0)/jenkins-deb-common ] || exit 1
. $(dirname $0)/jenkins-deb-common

jenkins_init
jenkins_set_vars

function err_cleanup_oz_image_build() {
    # $1 - name
    if [ "${NOCLEAN-0}" == "1" ]; then
    exit 0
    fi

    sudo virsh destroy ${1}
    sleep 5
    sudo lvremove -f ${LVM_ROOT}/${1}
    exit 1
}

kvm_instance_name=${BINARY_BUILD_RELEASE}-oz-image-build

# this sets IP as a side-effect
get_ip $kvm_instance_name

MEMORY=2048000

maybe_make_kvm_instance $kvm_instance_name
start_kvm_instance $kvm_instance_name ${IP} http://build.monkeypuppetlabs.com/packages ${BINARY_BUILD_RELEASE} ${NOVA_RELEASE}-${MILESTONE}

trap "err_cleanup_oz_image_build ${kvm_instance_name}" SIGINT SIGTERM EXIT ERR

sleep 20s

# add our custom deb to the build environment
ssh root@${IP} "DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes install git nfs-common python-support genisoimage gvncviewer libvirt-dev mtools python-libxml2 python-libvirt python-pycurl python-numpy python-m2crypto python-parted libaugeas0 libhivex0 febootstrap qemu-system kvm qemu-kvm qemu btrfs-tools cryptsetup diff grub-pc ntfs-3g ntfsprogs reiserfsprogs zfs-fuse binutils dosfstools jfsutils lsof lvm2 parted scrub strace xfsprogs zerofree"

ssh root@${IP} "wget http://libguestfs.org/download/binaries/ubuntu1104-packages/python-guestfs_1.15.11-1_amd64.deb"
ssh root@${IP} "wget http://libguestfs.org/download/binaries/ubuntu1104-packages/libguestfs0_1.15.11-1_amd64.deb"
ssh root@${IP} "wget http://libguestfs.org/download/binaries/ubuntu1104-packages/febootstrap_3.12-1_amd64.deb"

ssh root@${IP} "dpkg -i /root/febootstrap_3.12-1_amd64.deb"
ssh root@${IP} "dpkg -i /root/libguestfs0_1.15.11-1_amd64.deb"
ssh root@${IP} "dpkg -i /root/python-guestfs_1.15.11-1_amd64.deb"

ssh root@${IP} "mkdir -p /srv/nfs-scratch"
ssh root@${IP} "mount -t nfs 184.106.53.105:/srv/export/nfs-scratch  /srv/nfs-scratch"
ssh root@${IP} "git clone git://github.com/rackerjoe/oz-image-build.git"
ssh root@${IP} "dpkg -i /root/oz-image-build/packages/oz_0.8.0-1_all.deb"
ssh root@${IP} "umount /srv/nfs-scratch"

trap - SIGINT SIGTERM EXIT ERR

sudo virsh destroy ${kvm_instance_name}
sleep 5
sudo lvremove -f ${LVM_ROOT}/${kvm_instance_name}

