#!/bin/bash
#
# $1 = test repo number
#

# force a local default so this can be run on command line
DISTRELEASE=${DISTRELEASE-ubuntu-precise}
PACKAGE_REPO=${PACKAGE_REPO-proposed-packages}

[ -e $(dirname $0)/jenkins-deb-common ] || exit 1
. $(dirname $0)/jenkins-deb-common

jenkins_init
jenkins_set_vars

kvm_instance_name=${BINARY_BUILD_RELEASE}-Essex-Allinone

# this sets IP as a side-effect
get_ip $kvm_instance_name

function err_cleanup_chef() {
    # $1 - name
    if [ "${NOCLEAN-0}" == "1" ]; then
        exit 0
    fi

    # Delete node and client from chef-server
    ssh root@${IP} 'knife node delete $HOSTNAME -y'
    ssh root@${IP} 'knife client delete $HOSTNAME -y'

    sudo virsh destroy ${1}
    sleep 5
    sudo lvremove -f ${LVM_ROOT}/${1}
    exit 1
}

MEMORY=2048000
if ! maybe_make_kvm_instance $kvm_instance_name; then
    echo "Unable to create KVM Instance"
    exit 1
fi
trap "err_cleanup_chef ${kvm_instance_name}" SIGINT SIGTERM EXIT ERR
start_kvm_instance $kvm_instance_name ${IP} http://archive.ubuntu.com/ubuntu precise main

if [ ${BINARY_BUILD_VARIANT} = "debian" ]; then
    ssh root@${IP} apt-get install vlan -y --force-yes
else
    ssh root@${IP} yum -y --exclude=kernel* update
    ssh root@${IP} yum install -y vconfig perl gcc make yum-fastestmirror
fi

ssh root@${IP} vconfig add eth0 100
ssh root@${IP} vconfig add eth0 101

if [ ${BINARY_BUILD_VARIANT} = "debian" ]; then
    # Trying to fix a bug
    count=1
    while ! ssh root@${IP} "DEBIAN_FRONTEND=noninteractive apt-get install cgroup-lite -y --force-yes"; do
        if [ $count -gt 3 ]; then
            echo "Unable to install cgroup-lite"
            exit 1
        fi
        if ! ( ssh root@${IP} "/usr/bin/cgroups-mount" ); then
            :
        fi 
        sleep 2;
        count=$(( count + 1 ));
    done
fi

# Install system pre-reqs
if [ ${BINARY_BUILD_VARIANT} = "debian" ]; then
  ssh root@${IP} "apt-get install -y wget curl build-essential automake"
else
  ssh root@${IP} "yum install -y wget tar"
fi

# Try to quiet installer
ssh root@${IP} 'echo "alias wget=\"wget -q\"" >> ~/.bashrc '

# Install ruby/chef via opscode's fullstack installer
if ! ( ssh root@${IP} "bash < <(curl -s http://s3.amazonaws.com/opscode-full-stack/install.sh)" ); then
    echo "Unable to install Opscode FullStack Installer"
    exit 1
fi

# Setup Hosted Chef
ssh root@${IP} 'wget -q http://c308412.r12.cf1.rackcdn.com/chef.tar.gz; tar -xvzf chef.tar.gz; /opt/opscode/bin/knife configure client ./client-config'
ssh root@${IP} 'mkdir /etc/chef; cp -r ~/client-config/* /etc/chef/; /opt/opscode/bin/chef-client'

ssh root@${IP} '/opt/opscode/bin/knife node run_list add $HOSTNAME role[jenkins-allinone]'
# ssh root@${IP} '/opt/opscode/bin/knife node run_list add $HOSTNAME recipe[kong]'
ssh root@${IP} '/opt/opscode/bin/knife node run_list add $HOSTNAME recipe[exerstack]'
ssh root@${IP} '/opt/opscode/bin/chef-client'

sleep 20s

# These tests are not working on essex yet
ssh root@${IP} 'rm -rf /opt/exerstack/exercises/bundle.sh'
ssh root@${IP} 'rm -rf /opt/exerstack/exercises/euca.sh'
# ssh root@${IP} 'rm -rf /opt/exerstack/exercises/glance.sh'
ssh root@${IP} 'rm -rf /opt/exerstack/exercises/keystone-manage.sh'

if ! ( ssh root@${IP} 'cd /opt/exerstack; ./exercise.sh' ); then
    echo "Exerstack test suite failed"
    exit 1
fi

trap - SIGINT SIGTERM EXIT ERR

# Delete node and client from chef-server
ssh root@${IP} '/opt/opscode/bin/knife node delete $HOSTNAME -y'
ssh root@${IP} '/opt/opscode/bin/knife client delete $HOSTNAME -y'

sudo virsh destroy ${kvm_instance_name}
sleep 5
sudo lvremove -f ${LVM_ROOT}/${kvm_instance_name}
