#!/bin/bash
#
# $1 = test repo number
#

# force a local default so this can be run on command line
DISTRELEASE=${DISTRELEASE-ubuntu-precise}
PACKAGE_REPO=${PACKAGE_REPO-proposed-packages}

set -e
set -x

[ -e $(dirname $0)/jenkins-deb-common ] || exit 1
. $(dirname $0)/jenkins-deb-common

jenkins_init
jenkins_set_vars

# Get defined branch of chef-cookbooks
git clone --recursive --branch ${GIT_BRANCH} https://github.com/rcbops/chef-cookbooks/

# Grab knife config etc..
cp -r ~/.chef chef-cookbooks

# Knife upload cookbooks to hosted chef
cd chef-cookbooks
# using rake to make this easier
rake upload_cookbooks
rake roles
#for i in `ls cookbooks`; do
#  knife cookbook upload $i
#done

cd ..

# Cleanup after ourselves
rm -rf chef-cookbooks
