#!/bin/bash
#
# $1 = test repo number
#
env
# JENKINS COMMON
[ -e $(dirname $0)/jenkins-deb-common ] || exit 1
. $(dirname $0)/jenkins-deb-common
jenkins_init
jenkins_set_vars

# Hide ipmi info
source ~jenkins/.ipmirc

# SETUP ISO NAME
MILESTONE="d5"
if [ -z "$NOVA_RELEASE" ] || [ -z "$MILESTONE" ] || [ -z "$DISTRELEASE" ]; then
    ISONAME="crowbar.iso"
else
    BINARY_BUILD_RELEASE=`echo $DISTRELEASE | cut -d'-' -f2`
    ISONAME="crowbar-rcb-${NOVA_RELEASE}-${MILESTONE}-${BINARY_BUILD_RELEASE}.iso"
fi

# EXEC CROWBAR BUILD / BOOT ADMIN NODE
ssh openstack@${ISODEST} "sudo /home/openstack/incoming/fixup_crowbar.sh ${ISONAME}"
ssh openstack@${IPMIHOST} "ipmitool -I lanplus -H ${DRACIP} -U ${DRACUSER} -P ${DRACPASS} chassis bootdev pxe; ipmitool -I lanplus -H ${DRACIP} -U ${DRACUSER} -P ${DRACPASS} chassis power cycle"

# WAIT TO ENSURE TARGET GOES DOWN FOR REBOOT
sleep 120

# WAIT FOR ADMIN NODE TO HAVE SSH
# This takes ~30 mins
# while true; do nc -z 184.106.53.10 22 && break; echo 'Waiting for remote sshd...'; sleep 60; done
count=1
while [ $count -lt 35 ]; do
    count=$(( count + 1 ))
    sleep 60s
    if ( nc 184.106.53.10 22 -w 1 -q 0 < /dev/null ); then
        break
    fi
done
sleep 5

# SSH TO ADMIN NODE 
SSH_OPTS='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
HEADNODE='184.106.53.10'
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar node_state status | grep -e crowbar | grep -e Ready' ); then
    echo "Crowbar Headnode does not appear to have installed correctly"
    exit 1
fi
