#!/bin/bash
#
# $1 = test repo number
#

# force a local default so this can be run on command line
if [ -z $DISTRELEASE ]; then
    DISTRELEASE=fedora16_x86_64
fi

[ -e $(dirname $0)/jenkins-deb-common ] || exit 1
. $(dirname $0)/jenkins-deb-common

jenkins_init
jenkins_set_vars

function err_cleanup_oz_image_build() {
    # $1 - name
    if [ "${NOCLEAN-0}" == "1" ]; then
    exit 0
    fi

    exit 1
}

cd ~/oz-image-build
git reset --hard HEAD
git pull
if [ $FORCE -eq 0 ]; then
    sudo make $DISTRELEASE-clean
fi
sudo make $DISTRELEASE
