#!/bin/bash
#
# $1 = test repo number
#

# force a local default so this can be run on command line
DISTRELEASE=fedora-beefy

[ -e $(dirname $0)/jenkins-deb-common ] || exit 1
. $(dirname $0)/jenkins-deb-common

jenkins_init
jenkins_set_vars

kvm_instance_name=fedora-beefy-update

# this sets IP as a side-effect
get_ip $kvm_instance_name

function err_cleanup() {
    # $1 - name
    if [ "${NOCLEAN-0}" == "1" ]; then
        exit 0
    fi

    sudo virsh destroy ${1}
    sleep 5
    sudo lvremove -f ${LVM_ROOT}/${1}
    exit 1
}

MEMORY=2048000
maybe_make_kvm_instance $kvm_instance_name
trap "err_cleanup ${kvm_instance_name}" SIGINT SIGTERM ERR
start_kvm_instance $kvm_instance_name ${IP} http://archive.ubuntu.com/ubuntu precise main

ssh root@${IP} yum -y --exclude=kernel* update

sleep 20s

trap - SIGINT SIGTERM EXIT ERR

sudo virsh destroy ${kvm_instance_name}
sleep 5

# here we need to merge the snapshot back into the original
sudo lvremove -f ${LVM_ROOT}/${kvm_instance_name}
