#!/bin/bash

[ -e $(dirname $0)/jenkins-deb-common ] || exit 1
. $(dirname $0)/jenkins-deb-common

jenkins_init
jenkins_set_vars

set

if [ "${1-}" != "" ]; then
    promote_repo $1
else
    promote_repo
fi


