#!/bin/bash
#
# $1 = test repo number
#
env
# JENKINS COMMON
[ -e $(dirname $0)/jenkins-deb-common ] || exit 1
. $(dirname $0)/jenkins-deb-common
jenkins_init
jenkins_set_vars

# Hide ipmi info
source ~jenkins/.ipmirc

# SETUP ISO NAME
MILESTONE="d5"
if [ -z "$NOVA_RELEASE" ] || [ -z "$MILESTONE" ] || [ -z "$DISTRELEASE" ]; then
    ISONAME="crowbar.iso"
else
    BINARY_BUILD_RELEASE=`echo $DISTRELEASE | cut -d'-' -f2`
    ISONAME="crowbar-rcb-${NOVA_RELEASE}-${MILESTONE}-${BINARY_BUILD_RELEASE}.iso"
fi

# EXEC CROWBAR BUILD / BOOT ADMIN NODE
ssh openstack@${ISODEST} "sudo /home/openstack/incoming/fixup_crowbar.sh ${ISONAME}"
ssh openstack@${IPMIHOST} "ipmitool -I lanplus -H ${DRACIP} -U ${DRACUSER} -P ${DRACPASS} chassis bootdev pxe; ipmitool -I lanplus -H ${DRACIP} -U ${DRACUSER} -P ${DRACPASS} chassis power cycle"

# POWER OFF CONTROLLER NODE
ssh openstack@${IPMIHOST} "ipmitool -I lanplus -H ${CONTROLLERIP} -U ${DRACUSER} -P ${DRACPASS} chassis bootdev pxe; ipmitool -I lanplus -H ${CONTROLLERIP} -U ${DRACUSER} -P ${DRACPASS} chassis power off"

# WAIT TO ENSURE TARGET GOES DOWN FOR REBOOT
sleep 60s

# WAIT FOR ADMIN NODE TO HAVE SSH
# This takes ~30 mins
# while true; do nc -z 184.106.53.10 22 && break; echo 'Waiting for remote sshd...'; sleep 60; done
count=1
while [ $count -lt 35 ]; do
    count=$(( count + 1 ))
    sleep 60s
    if ( nc ${HEADNODE} 22 -w 1 -q 0 < /dev/null ); then
        break
    fi
done

SSH_OPTS='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'

count=1
while [ $count -lt 10 ]; do
    count=$(( count + 1 ))
    sleep 60s
    # SSH TO ADMIN NODE 
    if ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_node_state status | grep -e crowbar | grep -e Ready' ); then
        break
    fi
done

if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_node_state status | grep -e crowbar | grep -e Ready' ); then
    echo "Installation of Crowbar Headnode failed"
    exit 1
fi

sleep 120s

# POWER ON CONTROLLER NODE 
ssh openstack@${IPMIHOST} "ipmitool -I lanplus -H ${CONTROLLERIP} -U ${DRACUSER} -P ${DRACPASS} chassis bootdev pxe; ipmitool -I lanplus -H ${CONTROLLERIP} -U ${DRACUSER} -P ${DRACPASS} chassis power on"

# WAIT TO ENSURE TARGET GOES DOWN FOR REBOOT
sleep 60s

## Loop and wait for the Controller node to get discovered
count=1
while [ $count -lt 15 ]; do
    count=$(( count + 1 ))
    sleep 60s
    if ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_node_state status --no-ready | grep d60-eb-69-8f-73-6c' ); then
        echo "Controller node discovered"
        break 
    fi
done
sleep 5

if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_node_state status --no-ready | grep d60-eb-69-8f-73-6c' ); then
    echo "Something went wrong with discovering the Controller node"
    exit 1
fi

##################################################
# Push MYSQL Proposal
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_mysql proposal create jenkins' ); then
    echo "Unable to create the MySQL Proposal"
    exit 1
fi

## Ghetto Hack since we are disabling IPMI Barclamp
## SET PXE BOOT on CONTROLLER NODE 
ssh openstack@${IPMIHOST} "ipmitool -I lanplus -H ${CONTROLLERIP} -U ${DRACUSER} -P ${DRACPASS} chassis bootdev pxe"

if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_mysql proposal commit jenkins' ); then
    echo "Unable to commit the MySQL Proposal"
    exit 1
fi

# Loop and wait for the MySQL Proposal to get applied
count=1
while [ $count -lt 30 ]; do
    count=$(( count + 1 ))
    sleep 60s
    if ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_mysql list | grep jenkins' ); then
        echo "MySQL proposal successfully applied"
        break
    fi

    if [ $count == 29 ]; then
        echo "MySQL Proposal not successfully applied"
        exit 1
    fi
done
##################################################

##################################################
# Push the Keystone Proposal
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_keystone proposal create jenkins' ); then
    echo "Unable to create the Keystone Proposal"
    exit 1
fi
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_keystone proposal commit jenkins' ); then
    echo "Unable to commit the Keystone Proposal"
    exit 1
fi
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_keystone list | grep jenkins' ); then
    echo "Keystone proposal not applied"
    exit 1
fi
##################################################

##################################################
# Push the Glance Proposal
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_glance proposal create jenkins' ); then
    echo "Unable to create the Glance Proposal"
    exit 1
fi
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_glance proposal commit jenkins' ); then
    echo "Unable to commit the Glance Proposal"
    exit 1
fi
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_glance list | grep jenkins' ); then
    echo "Glance proposal not applied"
    exit 1
fi
##################################################

##################################################
# Push the Nova Proposal
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova proposal create jenkins' ); then
    echo "Unable to create the Nova Proposal"
    exit 1
fi
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova proposal commit jenkins' ); then
    echo "Unable to commit the Nova Proposal"
    exit 1
fi
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova list | grep jenkins' ); then
    echo "Nova proposal not applied"
    exit 1
fi
##################################################

##################################################
# Push the Dash Proposal
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova_dashboard proposal create jenkins' ); then
    echo "Unable to create the Dash Proposal"
    exit 1
fi
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova_dashboard proposal commit jenkins' ); then
    echo "Unable to commit the Dash Proposal"
    exit 1
fi
if ! ( ssh ${SSH_OPTS} crowbar@${HEADNODE} 'sudo -i /opt/dell/bin/crowbar_nova_dashboard list | grep jenkins' ); then
    echo "Dash proposal not applied"
    exit 1
fi
##################################################
