#!/bin/bash

set -x
set -e
set -u

# Cleanup
rm -rf ./* || :
rm -rf ./.* || :

# Clone the upstream repo
if ! ( git clone ${GIT_REPO} ./ ); then
    echo "Unable to clone git repo: ${GIT_REPO}"
    exit 1
fi

# Run knife cookbook test against the submodule
if ! ( ./run_tests.sh -c -V ); then
    echo "Test suite check failed"
    exit 1
fi
